/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package explorasi;

import edu.stanford.smi.protegex.owl.inference.reasoner.exception.ProtegeReasonerException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tirta Wening Rachman
 */
public class GameJFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameJFrame
     * @throws edu.stanford.smi.protegex.owl.inference.reasoner.exception.ProtegeReasonerException
     */
    public GameJFrame() throws ProtegeReasonerException {
        this.tUtil = TransportationUtil.getInstance();
        currentStep = 0;
        namaKendaraan = "";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaQuestion = new javax.swing.JTextArea();
        jTextFieldAns = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jButtonRestart = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaQuestion.setEditable(false);
        jTextAreaQuestion.setColumns(20);
        jTextAreaQuestion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaQuestion);

        jTextFieldAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnsActionPerformed(evt);
            }
        });

        jLabel1.setText("Jawaban:");

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jButtonRestart.setText("Start");
        jButtonRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAns, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonRestart)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSubmit)))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSubmit)
                    .addComponent(jButtonRestart))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnsActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:
        if(isAlreadyStarted){
            if(currentStep == 0){
                namaKendaraan = jTextFieldAns.getText();
            }else if(currentStep <= 7){
                int tmp = Integer.parseInt(jTextFieldAns.getText());
                switch(currentStep){
                    case 1:
                        aturan.put("hasModa", tmp == 3 ? "Udara" : tmp == 2 ? "Laut" : "Darat");
                        if(tmp != 1){
                            currentStep++;
                        }
                        break;
                    case 2:
                        aturan.put("hasJumlahRoda", tmp == 1 ? "NULL" : tmp == 2 ? "Dua" : tmp == 3 ? "Tiga" : tmp == 4 ? "Empat" : "LebihDariEmpat");
                        break;
                    case 3:
                        aturan.put("hasAkses", tmp == 1 ? "Publik" : "Pribadi");
                        break;
                    case 4:
                        aturan.put("hasLoad", tmp == 1 ? "Penumpang" : "Barang");
                        break;
                    case 5:
                        aturan.put("hasKeperluan", tmp == 1 ? "Perang" : "Transportasi");                        
                        break;
                    case 6:
                        aturan.put("hasSumberTenaga", tmp == 1 ? "Angin" : tmp == 2 ? "Solar" : tmp == 3 ? "Avtur" : tmp == 4 ? "Manusia" : tmp == 5 ? "BatuBara" : tmp == 6 ? "Listrik" : "Bensin");
                        break;
                    case 7:
                        aturan.put("hasModeTransmisi", tmp == 2 ? "Manual" : tmp == 3 ? "Semi-Automatic" : tmp == 4 ? "Automatic" : "NULL");
                        break;

                }
            }
            jTextFieldAns.setText("");
            System.out.println("currentStep = " + currentStep);
            if(currentStep < 7){
                currentStep++;
                jTextAreaQuestion.setText(questions[currentStep]);
            }else{
                
                List<String> hsl = tUtil.conclude(namaKendaraan.replaceAll(" ", "_"), aturan); //path nya ga boleh mengandung spasi , gatau kenapa? -_-
                String tStr = namaKendaraan + " adalah:\n";
                for(String s: hsl){
                    tStr = tStr + s + "\n";
                }
                jTextAreaQuestion.setText(tStr);
            }
        }
        
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jButtonRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestartActionPerformed
        // TODO add your handling code here:
        resetGame();
        startGame();
    }//GEN-LAST:event_jButtonRestartActionPerformed
    
    
    Map<String, String> aturan = new HashMap<>();
    int currentStep;
    boolean isAlreadyStarted = false;
    String namaKendaraan;
    TransportationUtil tUtil;
    String[] questions = {
        "Apa nama kendaraan anda?",
        "Dimana kendaraan berjalan?\n1. Darat\n2. Laut\n3. Udara\n\n(pilih satu)",
        "Secara umum, Berapa jumlah roda pada kendaraan ini?\n1. Tidak memiliki roda\n2. Dua\n3. Tiga\n4. Empat\n5. Lebih dari Empat\n\n(Pilih satu)",
        "Apakah kendaraan ini bersifat Publik atau Pribadi?\n1. Publik\n2. Pribadi\n\n(Pilih satu)",
        "Apa yang diangkut oleh kendaraan anda?\n1. Penumpang\n2. Barang\n\n(Pilih satu)",
        "Digunakan untuk apakah kendaran tersebut?\n1. Perang\n2. Transportasi\n\n(Pilih satu)",
        "Bahan bakar apakah yang digunakan oleh kendaraan ini?\n1. Angin\n2. Solar\n3. Avtur\n4. Manusia\n5. Batubara\n6. Listrik\n7. Bensin\n\n(Pilih satu)",
        "Mode Transmisi seperti apa yang digunakan pada kendaran ini?\n1. Tidak diketahui\n2. Manual\n3. Semi-automatic\n4. Automatic\n\n(Pilih satu)"
    };
    
    /**
     * @param args the command line arguments
     * @throws edu.stanford.smi.protegex.owl.inference.reasoner.exception.ProtegeReasonerException
     */
    public static void main(String args[]) throws ProtegeReasonerException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new GameJFrame().setVisible(true);
                } catch (ProtegeReasonerException ex) {
                    Logger.getLogger(GameJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        
        
        
        
    }
    
    public void resetGame(){
        aturan = new HashMap<>();
        currentStep = 0;
        jTextAreaQuestion.setText(questions[currentStep]);
    }

    public void startGame(){
        resetGame();
        jButtonRestart.setText("Restart");
        isAlreadyStarted = true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRestart;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaQuestion;
    private javax.swing.JTextField jTextFieldAns;
    // End of variables declaration//GEN-END:variables
}
